# Site settings
title: 刘江湖的博客
header-img: img/home-bg.jpg
email: liujianghu@outlook.com
description: "极品拖拉机，刘江湖, golang, c#, web 开发,高性能，大数据, 互联网, .net"
baseurl: ""
url: "http://liujianghu.github.io"
github_username:  liujianghu

# Build settings

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

highlighter: pygments
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]

# Duoshuo settings
duoshuo_username: liujianghu
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing

RSS: false
