# Site settings
title: 极品拖拉机
header-img: img/home-bg.jpg
email: liujianghu@outlook.com
description: "极品拖拉机，刘江湖,golang,c#，高性能，大数据"
baseurl: ""
url: "http://liujianghu.github.io"
github_username:  liujianghu

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]
